services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: python3 main.py
    depends_on:
      - target
    cap_add:
      - SYS_PTRACE

  target:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # These placeholders will be replaced by the script
        - CFLAGS=%%TARGET_CFLAGS%%
        - TARGET_BINARY=%%TARGET_BINARY%%
    ports:
      - "8080:8080"
    privileged: true 
    # The entrypoint will read the variables from this file
    entrypoint: >
      sh -c "echo ${ASLR_SETTING} > /proc/sys/kernel/randomize_va_space && 
             ./entrypoint.sh %%TARGET_BINARY%%"

networks:
  default:
    driver: bridge