version: '3.8'

services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    env_file:
      - .env
      - run.env
    volumes:
      - .:/app
    working_dir: /app
    command: python3 main.py
    depends_on:
      - target
    cap_add:
      - SYS_PTRACE

  target:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_BINARY=${TARGET_BINARY}
    env_file:
      - run.env
    ports:
      - "8080:8080"
    privileged: true
    # The command is now handled by the ENTRYPOINT in the Dockerfile