services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: python3 main.py
    depends_on:
      - target
    cap_add:
      - SYS_PTRACE

  target:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    # Privileged is still needed for GDB to attach properly
    privileged: true

networks:
  default:
    driver: bridge