# No version needed for modern Docker Compose
services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    env_file:
      - .env
      - run.env
    volumes:
      - .:/app
      # --- THIS IS THE CRITICAL CHANGE ---
      # Mount the Docker socket to allow the agent to run 'docker exec'
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: python3 main.py
    depends_on:
      - target
    cap_add:
      - SYS_PTRACE

  target:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TARGET_BINARY=${TARGET_BINARY}
    env_file:
      - run.env
    ports:
      - "8080:8080"
    privileged: true
    command: >
      sh -c "echo ${ASLR_SETTING} > /proc/sys/kernel/randomize_va_space && 
             echo 'ASLR set to:' && 
             cat /proc/sys/kernel/randomize_va_space && 
             python3 gdb_mcp_server.py"