services:
  agent:
    build:
      context: .
      dockerfile: Dockerfile.agent
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /app
    command: python3 main.py --target %%TARGET_BINARY%%
    depends_on:
      - target
    cap_add:
      - SYS_PTRACE

  target:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CFLAGS=%%TARGET_CFLAGS%%
        - TARGET_BINARY=%%TARGET_BINARY%%
    ports:
      - "8080:8080"
    privileged: true 

networks:
  default:
    driver: bridge